# Generated by Django 4.2.7 on 2024-01-02 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_order_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='completed',
            new_name='is_completed',
        ),
    ]
